-- |
-- Module      : CSMT.Verify.CompletenessSpec
-- Description : Cross-check @csmt-verify@'s completeness verifier
-- Copyright   : (c) Paolo Veronelli, 2024
-- License     : Apache-2.0
--
-- The @csmt-verify@ sublibrary provides a pure verifier for
-- completeness proofs ('CSMT.Verify.verifyCompletenessProof').
-- This spec checks the round-trip (write side renders → wire bytes
-- → verifier bytes-in path) on real proofs generated by the
-- database-backed @generateProof@, plus the empty-leaves case
-- exercised by @POST /tx/oracle/end@ in the
-- @cardano-mpfs-offchain@ proof redesign (#243).
module CSMT.Verify.CompletenessSpec (spec) where

import CSMT
    ( Direction (..)
    , Standalone (StandaloneCSMTCol)
    )
import CSMT.Backend.Pure
    ( runPureTransaction
    )
import CSMT.Core.CBOR (renderCompletenessProof)
import CSMT.Hashes (Hash, hashHashing, mkHash, renderHash)
import CSMT.Interface (Hashing (..), Indirect (..))
import CSMT.Proof.Completeness
    ( CompletenessProof
    , generateProof
    )
import CSMT.Test.Lib
    ( evalPureFromEmptyDB
    , hashCodecs
    , indirect
    , insertHashes
    , intHash
    , manyRandomPaths
    )
import CSMT.Verify qualified as Verify
import Data.Bits (xor)
import Data.ByteString (ByteString)
import Data.ByteString qualified as B
import Data.List (sort)
import Data.Word (Word8)
import Database.KV.Transaction (query)
import Test.Hspec (Spec, describe, it, shouldBe)
import Test.Hspec.QuickCheck (prop)
import Test.QuickCheck
    ( Gen
    , arbitrary
    , forAll
    , listOf
    , vectorOf
    , (===)
    )

-- | Generate a completeness proof against the empty prefix on a
-- random tree of hashes, returning the bytes the verifier would
-- see on the wire.
genTreeProof
    :: Gen
        ( ByteString -- root bytes
        , [Indirect Hash] -- sorted leaves
        , ByteString -- proof bytes
        )
genTreeProof = do
    ks <- manyRandomPaths
    let values = zipWith indirect ks (intHash <$> [1 ..])
        (mp, mr) = evalPureFromEmptyDB $ do
            insertHashes values
            mp' <-
                runPureTransaction hashCodecs
                    $ generateProof StandaloneCSMTCol [] []
            mr' <-
                runPureTransaction hashCodecs
                    $ query StandaloneCSMTCol []
            pure (mp', mr')
    case (mp, mr) of
        (Just proof, Just rootIndirect) ->
            pure
                ( renderHash (rootHash hashHashing rootIndirect)
                , sort values
                , renderCompletenessProof
                    (proof :: CompletenessProof Hash)
                )
        _ ->
            -- Fallback for the empty-tree case: render an empty proof
            -- against a dummy root. The properties below still bind
            -- the values to the proof.
            pure (B.replicate 32 0, [], B.empty)

genBS :: Gen ByteString
genBS = B.pack <$> listOf (arbitrary :: Gen Word8)

spec :: Spec
spec = describe "csmt-verify completeness" $ do
    prop "round-trips real proofs and verifies under matching root"
        $ forAll genTreeProof
        $ \(rootBs, values, proofBs) ->
            -- Empty trees are skipped: the fallback produces empty
            -- bytes that legitimately fail to parse.
            B.null proofBs
                || Verify.verifyCompletenessProof
                    rootBs
                    []
                    values
                    proofBs

    prop "rejects a tampered root"
        $ forAll genTreeProof
        $ \(rootBs, values, proofBs) ->
            let badRoot = B.map (`xor` 0xff) rootBs
            in  B.null proofBs
                    || not
                        ( Verify.verifyCompletenessProof
                            badRoot
                            []
                            values
                            proofBs
                        )

    prop "rejects garbage proof bytes"
        $ forAll ((,) <$> vectorOf 32 arbitrary <*> genBS)
        $ \(rootBs, garbage) ->
            Verify.verifyCompletenessProof
                (B.pack rootBs)
                []
                []
                garbage
                === False

    it "the wire format round-trips a hand-built proof" $ do
        -- Decoder/encoder symmetry on an already-known proof so we
        -- catch CBOR layout drift even when no tree is involved.
        let values =
                [ indirect [L, L, L, L] (mkHash "leaf-1")
                , indirect [R, R, R, R] (mkHash "leaf-2")
                ]
            (mp, _) = evalPureFromEmptyDB $ do
                insertHashes values
                mp' <-
                    runPureTransaction hashCodecs
                        $ generateProof StandaloneCSMTCol [] []
                mr' <-
                    runPureTransaction hashCodecs
                        $ query StandaloneCSMTCol []
                pure (mp' :: Maybe (CompletenessProof Hash), mr')
        case mp of
            Just proof ->
                let bs = renderCompletenessProof proof
                in  Verify.parseCompletenessProof bs `shouldBe` Just proof
            Nothing -> error "expected a proof"
